### ISSUE TITLE
Proposal: consider adding new platform

### ISSUE THREAD

**Issue by Kuyantsev-VP** [jyguyomarch/awesome-conversational-ai#3]
I know one another platform that may be interesting for you. [Dasha](https://dasha.ai/) is designed to solve the same issues (conversational ai, conversational interfaces, etc) and it is pretty powerful. It is mostly aimed to build voice apps but the text is also fully supported. I suggest you to take a look at it :)

You may check out [this demo](https://github.com/dasha-samples/automated-hotel-receptionist
) to dive into this tech (launching the app requires signing up but it is totally free)

I spent some time working with it, so feel free to ask if you have any questions

Some links:
- [main page](https://dasha.ai/)
- [platform overview](https://docs.dasha.ai/en-us/default)
- [playground](https://playground.dasha.ai/) to test some demos in browser without registration

**Comment by jyguyomarch** [comment]
@Kuyantsev-VP added Dash to the Platform section. Kept the description simple but let me know if you would add something to it. And thx for the contribution!

**Comment by Kuyantsev-VP** [comment]
@jyguyomarch , no, that's fine :)
